set windows-shell := ["C:/tools/cygwin/bin/sh.exe","-c"]

default:
	just --list


backtrace := '0'


run crate *args:
	just watch 'cargo run -p {{crate}} --example {{args}}'

test crate *args:
	RUST_BACKTRACE={{backtrace}} cargo test -p {{crate}} --test sweet -- {{args}}

test-w crate *args:
	RUST_BACKTRACE={{backtrace}} just watch 'cargo test -p {{crate}} --test sweet -- -w {{args}}'

watch command:
	cargo watch -q --ignore '{**/mod.rs,justfile,.gitignore}' --ignore '**.{txt,md,wasm,wat}' --ignore '{output/,out/}' -- {{command}}

mod:
	just watch 'cargo run --manifest-path ../../forky/crates/forky_cli/Cargo.toml'


## Compiling
expand crate example:
	just watch 'cargo expand -p {{crate}} --example {{example}}'