// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
	docsSidebar: [
		'index',
		{
			type: 'category',
			label: 'Getting Started',
			items: [
				'getting-started/boards',
				'getting-started/flashing',
				'getting-started/hello-led',
			],
		},
	],
};

module.exports = sidebars;
