//AUTOGENERATED

//@ts-ignore external
@external('Console', 'log')
declare function _log(val_ptr: u32, val_len: u32): void;			
export function log(val: string): void {
	
	const val_ptr_str = String.UTF8.encode(val)
	let val_ptr = changetype<usize>($val_ptr_str)
	let val_len = val_ptr_str.byteLength
		
	_log(val_ptr, val_len)
}
	