set windows-shell := ["C:/tools/cygwin/bin/sh.exe","-c"]
# requires powershell because of CMAKE_OBJECT_PATH_MAX
# set shell := ["powershell.exe", "-c"]

port := 'COM3'
backtrace := '0'
# target-idf := '--target riscv32imc-esp-espidf "-Zbuild-std=std,panic_abort"
# ./export-esp.ps1 && \

build *args:
	RUST_BACKTRACE={{backtrace}} && \
	cargo build \
	--example {{args}} \

#remove speed if experiencing issues
# ./export-esp.ps1 && \
flash *args:
	cargo espflash {{port}} \
	--monitor \
	--release \
	--speed 921600 \
	--partition-table partitions.csv \
	--example {{args}}

save *args:
	cargo espflash save-image \
	ESP32-C3 ./esp.image \
	--partition-table partitions.csv \
	--release \
	--merge \
	--example {{args}} \

monitor *args:
	cargo espflash serial-monitor {{port}} \
	--speed 921600