set windows-shell := ["C:/tools/cygwin/bin/sh.exe","-c"]

port := 'COM3'
backtrace := '0'

default:
	just --list


build *args:
	RUST_BACKTRACE={{backtrace}} && \
	cargo build \
	--example {{args}} \

#remove speed if experiencing issues
flash *args:
	cargo espflash {{port}} \
	--monitor \
	--release \
	--speed 921600 \
	--partition-table partitions.csv \
	--example {{args}}

save *args:
	cargo espflash save-image \
	ESP32-C3 ./esp.image \
	--partition-table partitions.csv \
	--release \
	--merge \
	--example {{args}} \

monitor *args:
	cargo espflash serial-monitor {{port}} \
	--speed 921600

watch command:
	cargo watch -q --ignore '{**/mod.rs,justfile,.gitignore}' --ignore '**.{txt,md,wasm,wat}' --ignore '{output/,out/}' -- {{command}}

mod:
	just watch 'cargo run --target x86_64-pc-windows-msvc --manifest-path ../../../forky/crates/forky_cli/Cargo.toml'

# Archive
# requires powershell because of CMAKE_OBJECT_PATH_MAX
# set shell := ["powershell.exe", "-c"]
# not neeeded? ./export-esp.ps1 && \

# target-idf := '--target riscv32imc-esp-espidf "-Zbuild-std=std,panic_abort"